import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Home',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'inventory',
        path: '',
        title: 'Inventory',
        translateKey: 'nav.inventory.inventory',
        icon: 'inventory',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['inventory.view', 'inventory.manage'],
        subMenu: [
            {
                key: 'inventory.products',
                path: '/inventory/products',
                title: 'Products & Variants',
                translateKey: 'nav.inventory.products',
                icon: 'inventory.products',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['inventory.view'],
                subMenu: [],
            },
            {
                key: 'inventory.warehouses',
                path: '/inventory/warehouses',
                title: 'Warehouses & Bins',
                translateKey: 'nav.inventory.warehouses',
                icon: 'inventory.warehouses',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['inventory.view'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'purchasing',
        path: '',
        title: 'Purchasing',
        translateKey: 'nav.purchasing.purchasing',
        icon: 'purchasing',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['purchasing.view', 'purchasing.manage'],
        subMenu: [
            {
                key: 'purchasing.orders',
                path: '/purchasing/orders',
                title: 'Purchase Pipeline',
                translateKey: 'nav.purchasing.orders',
                icon: 'purchasing.orders',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['purchasing.view'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'sales',
        path: '',
        title: 'Sales',
        translateKey: 'nav.sales.sales',
        icon: 'sales',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['sales.view', 'sales.manage'],
        subMenu: [
            {
                key: 'sales.orders',
                path: '/sales/orders',
                title: 'Sales Workspace',
                translateKey: 'nav.sales.orders',
                icon: 'sales.orders',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['sales.view'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'pos',
        path: '',
        title: 'POS',
        translateKey: 'nav.pos.pos',
        icon: 'pos',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['pos.view', 'pos.manage'],
        subMenu: [
            {
                key: 'pos.register',
                path: '/pos/register',
                title: 'Register & Shifts',
                translateKey: 'nav.pos.register',
                icon: 'pos.register',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['pos.view'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'reports.analytics',
        path: '/reports/analytics',
        title: 'Reports & Analytics',
        translateKey: 'nav.reports.analytics',
        icon: 'reports.analytics',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['reports.view'],
        subMenu: [],
    },
    {
        key: 'support',
        path: '',
        title: 'Support',
        translateKey: 'nav.support.support',
        icon: 'support',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'support.userGuide',
                path: '/support/user-guide',
                title: 'User Guide',
                translateKey: 'nav.support.userGuide',
                icon: 'support.userGuide',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
